name: Bot Penarik Berita Otomatis Nusa-Media

on:
  schedule:
    # Menggunakan format Cron Syntax. 
    # Jadwal di bawah ini diatur agar otomatis menyala setiap hari pada jam 06:00 WIB / 08:00 WIT.
    - cron: '0 23 * * *'
  workflow_dispatch: # Baris ini opsional, berfungsi agar tombol "Run" muncul manual di halaman GitHub

jobs:
  ambil-berita:
    runs-on: ubuntu-latest

    steps:
      # 1. Mengambil kode proyek terkini dari repositori GitHub Anda
      - name: Checkout Repository Kode
        uses: actions/checkout@v4

      # 2. Menyiapkan lingkungan runtime Node.js di server virtual
      - name: Setup Runtime Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3. Mengunduh pustaka (termasuk @supabase/supabase-js) agar skrip bisa berjalan
      - name: Install Dependencies Proyek
        run: npm install

      # 4. Mengeksekusi file skrip injeksi database otomatis Anda
      - name: Eksekusi Skrip Penarik Berita
        run: node src/scripts/ambilBeritaOtomatis.js
