name: Run Datadog Synthetic tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.2.2

    - name: Run Datadog Synthetic tests
      # Menggunakan v4 resmi untuk mendukung Node.js 24 dan menghilangkan peringatan depresiasi
      uses: DataDog/synthetics-ci-github-action@v4
      with:
        api_key: ${{ secrets.DD_API_KEY }}
        app_key: ${{ secrets.DD_APP_KEY }}
        test_search_query: 'tag:e2e-tests'
